const commentsTypes = {
  LOAD: "LOAD_COM",
  LOADED: "LOADED_COM",
  VOTE: "VOTE_COM",
  VOTED: "VOTED_COM",
  FORM_VALUE_CHANGED: "FORM_VALUE_CHANGED_COM",
  OPEN_NEW_FORM: "OPEN_NEW_FORM_COM",
  OPEN_EDIT_FORM: "OPEN_EDIT_FORM_COM",
  CLOSE_FORM: "CLOSE_FORM_COM",
  CREATE: "CREATE_COM",
  CREATED: "CREATED_COM",
  UPDATE: "UPDATE_COM",
  UPDATED: "UPDATED_COM",
  DELETE: "DELETE_COM",
  DELETED: "DELETED_COM"
};

export default commentsTypes;
