const typesPost = {
  REQUEST_ALL: 'REQUEST_ALL_POST',
  RECEIVE_ALL: 'RECEIVE_ALL_POST',
  REQUEST_BY_CATEGORY: 'REQUEST_BY_CATEGORY_POST',
  RECEIVE_BY_CATEGORY: 'RECEIVE_BY_CATEGORY_POST',
  REQUEST: 'REQUEST_POST',
  RECEIVE: 'RECEIVE_POST',
  REQUEST_ERROR: 'REQUEST_ERROR_POST',
  FORM_VALUE_CHANGED: 'FORM_VALUE_CHANGED_POST',
  LOAD_EDIT: 'LOAD_EDIT_POST',
  UPDATE: 'UPDATE_POST',
  UPDATED: 'UPDATED_POST',
  LOAD_NEW: 'LOAD_NEW_POST',
  CREATE: 'CREATE_POST',
  CREATED: 'CREATED_POST',
  DELETE: 'DELETE_POST',
  DELETED: 'DELETED_POST',
  VOTE: 'VOTE_POST',
  VOTED: 'VOTED_POST',
}

export default typesPost
